--@Author: MaurosMJ

SELECT
    s.username,
    o.object_name,
    o.object_type,
    decode(l.type, 'MR', 'Media Recovery Lock', 'RT', 'Redo Thread Lock',
           'BL', 'Buffer Cache Lock', 'CF', 'Control File Lock', 'CI',
           'Cross Instance Lock', 'CS', 'Control File Schema Lock', 'DF', 'Data File Lock',
           'DL', 'Direct Loader Lock', 'DM', 'Mount Lock', 'DR',
           'Distributed Recovery Lock', 'DX', 'Distributed Transaction Lock', 'FS', 'File Set Lock',
           'IN', 'Instance Lock', 'IR', 'Instance Recovery Lock', 'IS',
           'Instance State Lock', 'IV', 'Library Cache Invalidation Lock', 'JQ', 'Job Queue Lock',
           'KK', 'Redo Record Lock', 'LA', 'Library Cache Lock', 'LB',
           'Library Cache Lock', 'LC', 'Library Cache Lock', 'LD', 'Library Cache Lock',
           'LE', 'Library Cache Lock', 'LF', 'Library Cache Lock', 'LG',
           'Library Cache Lock', 'LH', 'Library Cache Lock', 'LI', 'Library Cache Lock',
           'LJ', 'Library Cache Lock', 'LK', 'Library Cache Lock', 'LL',
           'Library Cache Lock', 'LM', 'Library Cache Lock', 'LN', 'Library Cache Lock',
           'LO', 'Library Cache Lock', 'LP', 'Library Cache Lock', 'LQ',
           'Library Cache Lock', 'LR', 'Library Cache Lock', 'LS', 'Library Cache Lock',
           'LT', 'Library Cache Lock', 'LU', 'Library Cache Lock', 'LV',
           'Library Cache Lock', 'LW', 'Library Cache Lock', 'LX', 'Library Cache Lock',
           'LY', 'Library Cache Lock', 'LZ', 'Library Cache Lock', 'MR',
           'Media Recovery Lock', 'NA', 'Library Cache Lock', 'NB', 'Library Cache Lock',
           'NC', 'Library Cache Lock', 'ND', 'Library Cache Lock', 'NE',
           'Library Cache Lock', 'NF', 'Library Cache Lock', 'NG', 'Library Cache Lock',
           'NH', 'Library Cache Lock', 'NI', 'Library Cache Lock', 'NL',
           'Library Cache Lock', 'NM', 'Library Cache Lock', 'NN', 'Library Cache Lock',
           'NO', 'Library Cache Lock', 'NP', 'Library Cache Lock', 'NQ',
           'Library Cache Lock', 'NR', 'Library Cache Lock', 'NS', 'Library Cache Lock',
           'NT', 'Library Cache Lock', 'NU', 'Library Cache Lock', 'NV',
           'Library Cache Lock', 'NW', 'Library Cache Lock', 'NX', 'Library Cache Lock',
           'NY', 'Library Cache Lock', 'NZ', 'Library Cache Lock', 'PF',
           'Password File Lock', 'PR', 'Process Startup Lock', 'PS', 'Parallel Slaves Lock',
           'PU', 'Parallel Users Lock', 'RT', 'Redo Thread Lock', 'SC',
           'System Commit Number Lock', 'SH', 'Shared Pool Lock', 'SM', 'SMON Lock',
           'SN', 'Sequence Number Lock', 'SQ', 'Sequence Lock', 'SR',
           'System Range Lock', 'SS', 'Sort Segment Lock', 'ST', 'Space Transaction Lock',
           'SV', 'Sequence Number Value Lock', 'TA', 'Transaction Lock', 'TD',
           'Temporary Table Lock', 'TE', 'Extend Table Lock', 'TM', 'DML Queue Lock',
           'TO', 'Tablespace Offline Lock', 'TS', 'Temporary Segment Lock', 'TT',
           'Temporary Table Lock', 'TX', 'Transaction Lock', 'UN', 'User Name Lock',
           'WL', 'WL Enqueue Lock', 'WS', 'WS Enqueue Lock', 'XA',
           'Attribute Lock', 'XI', 'Instance Lock', 'XR', 'Row Exclusive Lock',
           'XS', 'Share Row Exclusive Lock', 'X', 'Row Share Lock', 'RS',
           'Row Share Lock', 'RX', 'Row Exclusive Lock', 'S', 'Share Lock',
           'SRX', 'Ges Enqueue Lock', 'SSX', 'GES Exclusive Lock', 'SI',
           'GES Intent Lock', 'XS', 'GES Share Lock', 'XT', 'Ges TM Lock',
           'ST', 'Ges TX Lock', 'DC', 'Deadlock Detector Lock', 'QA',
           'Instance Query Lock', 'QT', 'Instance Query Lock', 'UL', 'User-defined Lock') lock_type
FROM
         v$lock l
    JOIN all_objects o ON l.id1 = o.object_id
    JOIN v$session   s ON l.sid = s.sid;